openapi: 3.0.3
info:
  title: Answer API
  version: 1.0.0

servers:
  - url: http://localhost:8080/api/v1
    description: Local development server

paths:
  /question:
    post:
      summary: Get an answer based on context and question
      operationId: getAllAnswers
      x-method-extra-args:
        - "jakarta.servlet.http.HttpServletRequest request"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                question:
                  type: string
                  example: "Can I drink coffee?"
              required:
                - question
      responses:
        "200":
          description: Successful answer response
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer:
                    type: string
                    example: "Yes, you can drink coffee."
